name: update-docs

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.25
          cache: true
          cache-dependency-path: go.sum

      - name: Run PTerm-CI
        run: |
          go get
          go mod tidy
          go run . setup --ci
          go run . ptermCI

      - name: Push changes
        run: |
          git config --global user.name 'MagdielCAS'
          git config --global user.email 'magdiel.camp@gmail.com'
          
          if [[ -n $(git status -s) ]]; then
            git add .
            git commit -m "docs: update docs with PTerm-CI"
            git push origin HEAD:${GITHUB_REF}
          else
            echo "No changes to commit"
          fi
